apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-initdb-config
data:
    initdb.sql:
      SELECT schema_name FROM information_schema.schemata;
      CREATE SCHEMA inventory_schema AUTHORIZATION inventory;
        CREATE TABLE inventory_schema.author (
          id bigserial not null,
          first_name VARCHAR(100),
          last_name VARCHAR(100),
          created timestamp not null,
          created_by varchar(100) not null,
          modified timestamp not null,
          modified_by varchar(100) not null,
          PRIMARY KEY (id)
        );
      CREATE TABLE inventory_schema.book (
        id serial not null,
        title VARCHAR(100) NOT NULL,
        author_id int NOT NULL,
        published_date timestamp NOT NULL,
        isbn int,
        created timestamp not null,
        created_by varchar(100) not null,
        modified timestamp not null,
        modified_by varchar(100) not null,
        PRIMARY KEY (id),
        UNIQUE (isbn),
        CONSTRAINT fk_book_author_id_author_id foreign key (author_id) references inventory_schema.author
      );
      commit;
      SELECT COLUMN_NAME, DATA_TYPE FROM information_schema.COLUMNS WHERE TABLE_NAME = 'author';