apiVersion: v1
kind: PersistentVolume
metadata:
    name: docker-persistent-volume
spec:
    storageClassName: manual
    capacity:
        storage: 128M
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /data/docker-persistent-volume